### ISSUE TITLE
Change assembly instructions to help with glue in holes

### ISSUE THREAD

**Issue by gkholman** [CraneSoftwrights/board-baseball#128]
First, annotate the horizontal magnet holes on the back of level 5 with the opposite polarity as is shown on the front of level 5. Remember to annotate the vertical magnet slots as well, but with the same polarity as on the front.

Assemble the back of 4 onto the front of 5, 3 onto 4, 2 onto 3, and 1 onto 2.

When this assembly is fully dry (24 hours?) check that the holes all are clear of glue. Drill out from the back of 4 so as not to damage the front of 1.

Lay the assembly down with the back of 5 facing up. Place the magnets in the holes with the handwritten polarity indicated. Add adhesive to the back of 5 and add layer 6 and set to dry again.

**Comment by Gitgeorgeah** [comment]
I think that this would be an acceptable way to do it
