### ISSUE TITLE
Kathryn: Make a "one board" version (smaller holes?) for thicker wood, no compartment, no panel

### ISSUE THREAD

**Issue by gkholman** [CraneSoftwrights/board-baseball#132]

**Comment by gkholman** [comment]
Maybe start with a 3-board version with no compartment.

**Comment by Gitgeorgeah** [comment]
Are you thinking a 3 board version so that we can still have both game plays on it?

**Comment by gkholman** [comment]
Exactly. Or maybe even a two-board version with both game plays, no removable panel, and played with short stubby pegs. Or a one-board version burned on both sides.

But we can't just burn two sides of one board, or glue two full boards back-to-back because of the holes for balls and strikes necessarily not being symmetrical. Unless just for this one configuration we do make the holes symmetrical, but leave the holes asymmetrical for the deep boards. Or for this one configuration note the balls and strikes "backwards" ("strikes and balls") which is not standardized.

I think having the extra hole is the lesser of the two evils.

Hmmmm ... we could tell people just to prop the board between two books at top and bottom in order to get the needed depth for pegs.

**Comment by gkholman** [comment]
Hmmmmm ... the outs and innings indicators will be off as well, so perhaps I should redesign those to be symmetrical. But, again, there is a lot of thought put into the spacing of the holes.
