### ISSUE TITLE
Change the default branch to be main after testing QA

### ISSUE THREAD

**Issue by CraneSoftwrights** [CraneSoftwrights/board-baseball#201]
For the purposes of promotion during upcoming travel, I've changed the default branch to be the so-far-untested QA branch so that visitors to the site see the latest.

This is not the intended long-term behaviour, which is that only tested content be at the landing page. But it turns out there is no time to test the burn files before the travel.

This ticket is a reminder to change the default branch back to main after QA has been tested.

**Comment by gkholman** [comment]
Remember to change to /main/ in md2xhtml.sh
