### ISSUE TITLE
GAH: Possibly rearrange the text so the nine numbered items are across the top 123, 456, 789

### ISSUE THREAD

**Issue by gkholman** [CraneSoftwrights/board-baseball#39]

**Comment by Gitgeorgeah** [comment]
Do you understand what I meant when I made this comment?

I was thinking of having the instruction panel read more like
1   4   7
2   5   8
3   6   9

with the letter following below. It was to clean up some white space that was between the numbers and letter but in the latest release that I see that space has been removed as other items have been rearranged.

**Comment by Gitgeorgeah** [comment]
Latest prototype the text looked good. I think we can close this one
