### ISSUE TITLE
GAH: Are magnets needed for the upright play panel sitting in the instruction panel valley?

### ISSUE THREAD

**Issue by gkholman** [CraneSoftwrights/board-baseball#44]

**Comment by Gitgeorgeah** [comment]
I am unsure. This will need to be something that we test with a physical prototype. if the tolerance on the valley is close to the instruction panel size friction may hold it in place. If not, I am concerned that if the board is held at too much of an angle as if someone was sitting in a car with it that gravity would pull it down.

**Comment by gkholman** [comment]
I am convinced, now, that this is needed. I'm going to try and get it in ASAP for our next test build.
