### ISSUE TITLE
GAH: Cosmetic: Adjust the size of the bat on the rules panel

### ISSUE THREAD

**Issue by Gitgeorgeah** [CraneSoftwrights/board-baseball#65]
Looking at the rules panel, the bat icon for number 3 looks too large in the main SVG, better in the collage file, but still a little large. The bat for number 4 is just as large, but the butt of the bat is not appear under the colon as it does with number 3. Unsure if this is just a visual issue with my machine as the main SVG and collage SVG appear different when they shouldn't be.

**Comment by gkholman** [comment]
I kept the size the same and spaced it out for 3 as it is for 4.
